"""Aggregates all problem transformations"""
from .problems.longest_path import LongestPath
from .problems.graph_coloring import GraphColoring
from .problems.traveling_salesperson import TravelingSalesperson
from .problems.maximum_flow import MaximumFlow
from .problems.minimal_spanning_tree import MinimalSpanningTreeDegreeConstraint
from .problems.hamiltonian_cycle import HamiltonianCycle
from .problems.max_clique import MaxClique
from .problems.max_cut import MaxCut
