"""Aggregates all problem transformations"""
from .problems.clique_cover import CliqueCover
from .problems.densest_k_subgraph import DensestKSubgraph
from .problems.longest_path import LongestPath
from .problems.graph_coloring import GraphColoring
from .problems.traveling_salesperson import TravelingSalesperson
from .problems.maximum_flow import MaximumFlow
from .problems.minimal_spanning_tree import MinimalSpanningTreeDegreeConstraint
from .problems.hamiltonian_cycle import HamiltonianCycle
from .problems.max_clique import MaxClique
from .problems.max_cut import MaxCut
from .problems.minimum_vertex_cover import MinimumVertexCover
from .problems.maximum_independent_set import MaximumIndependentSet
